# Databricks接続設定
# 環境変数を使用してセキュアに認証情報を管理
dbt_core_databricks_ci:
  target: dev
  outputs:
    # 開発環境（ローカル開発用）
    # Personal Access Token (PAT) で認証
    dev:
      type: databricks
      catalog: sample_dev
      schema: staging
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

    # ステージング環境（PR時のCI/CD）
    # Service Principal で認証
    stg:
      type: databricks
      catalog: sample_stg
      schema: staging
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      auth_type: oauth
      client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}"
      client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}"
      threads: 4

    # 本番環境（Databricks Job経由）
    # Jobの実行コンテキストから自動取得（Service Principal不要）
    prod:
      type: databricks
      catalog: sample_prod
      schema: staging
      threads: 8
