#データベースから最初に入ってくるテーブルをここに定義(今回の場合はseed配下に入っているcsv名)
version: 2

sources:
  - name: main
    # schema指定を削除 - profiles.ymlのschema設定を使用
    tables:
      - name: 店舗マスタ
      - name: 商品マスタ
      - name: 注文
      - name: 注文明細
